### ISSUE TITLE
Add rate-limit detection & mitigation

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#10]
## Objective
When an HTTP call to the API fails due to a rate-limit error we want Nango to detect this and automatically implement an appropriate backoff strategy.

## Tasks
- [ ] Detect rate-limit issues by looking at response status code & headers
- [ ] Implement backoff (with `X-After` header if available)
- [ ] Add configuration per Integration to parametrize rate-limit detection & mitigation tactics
- [ ] Add proactive throttling if potential rate-limit issue is forecast (so we don't run into it)
- [ ] Make sure access token refresh is retried if it fails due to a rate-limit issue

Maybe out of scope for a first version but worth thinking about: Some rate-limits are for very long periods of time, eg. daily limit is exceeded. How should we handle these? If we just wait the main application may wait a veeery long time for `triggerAction` to complete (or run into issues itself if it is e.g. called from an AWS lambda which have ~15min timeout)

**Comment by cpursley** [comment]
This might be a pro (paid feature) :)

**Comment by bastienbeurier** [comment]
This should be mostly handled by the ability to configure specific retry policies (#45). If the need comes to do something more specific, let's reopen.
