### ISSUE TITLE
Automatically check & refresh OAuth access tokens

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#2]
## Objective
Automatically check access tokens for freshness (where possible) before each usage in `http_request` in the NangoAction class and automatically refresh it if needed.

## Tasks
- [x] Check token for freshness
- [x] Refresh token if required, log if refresh happened & store new tokens in Connections DB. If refresh fails the whole triggerAction should fail and return a message to the client

#### Docs
- [x] Update NangoAction.httpRequest reference with this new behaviour

**Comment by rguldener** [comment]
Done, see the referenced commit :-)
