### ISSUE TITLE
Add support for self-hosted deployment through private NPM registry

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#3]
## Objective
Allow the deployment of self-hosted Nango.
Currently the installation of the Nango Folder from an NPM package and the CLI around publishing that are missing.

## Tasks
- [ ] Add CLI tasks to publish the Nango Folder as an NPM package to a private registry (e.g. Github packages)
- [ ] Add support for package-based installation of the Nango Folder on the server

#### Docs
- [ ] Update self-hosted docs with necessary commands & ENV variable config of server

**Comment by bastienbeurier** [comment]
No longer needed (no more client-side integration files).
