### ISSUE TITLE
CLI: add-action command

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#5]
## Objective
Make it easy to add a new action by providing a command with the CLI to add a new action for an existing Integration.
Could look like this:
```npx nango add-action```

And maybe take optional parameters for the integration and name of the action. If omitted these could be asked from the user.
There is a scaffold for the action file that can be used in the [quickstart docs](https://docs.nango.dev/quickstart/node#create-an-action)

## Tasks
- [ ] Add the `add-action` command to the CLI
- [ ] Make sure the CLI has decent help built-in on how to use the command

#### Docs
- [ ] Update quickstart with CLI call instead of the touch & scaffold copy

**Comment by bastienbeurier** [comment]
No longer needed (no more client-side integration files).
