### ISSUE TITLE
Retry timed out HTTP requests

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#6]
## Objective
Automatically (and transparently) retry requests that initiate from `httpRequest` in NangoAction that time out. This probably indicates an issue with the external service and we should retry after a short pause to see if the service comes online again within a short period of time.

If retries fail more than pre-configured threshold they should fail permanently and a message should be logged.

## Tasks
- [ ] Add `max_retries` and `time_between_retries_sec` configuration options to nango-config.yaml and integrations.yaml
- [ ] Add retry logic to NangoAction.httpRequest implementation

#### Docs
- [ ] Update config reference with new configuration options
- [ ] Update NangoAction reference -> httpRequest section with new behaviour

**Comment by bastienbeurier** [comment]
Retries are now automatically handled by Temporal. And they do happen in case of request timeouts.

Since this issue is old and pre-date the current product, I'll create a new ticket to expose retry policy parameters in the Sync Config object.
