### ISSUE TITLE
Let client know about unrecoverable auth issues (expired/invalid tokens, refresh failed etc.) on server

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#7]
## Objective
If an action fails on the server because of some auth issue (e.g. access token revoked and we don't have a way to refresh it) there should be a way to let client(s) know: We cannot recover from this error without user interference. Letting the client know allows engineers using Nango to listen for these messages and then trigger an appropriate flow on their side.

Since this problem can happen at any point in time (when no client may be connected) we will publish a message on a queue for the client to listen to. The client SDK should then allow the app to register callbacks for incoming messages on this queue.

## Tasks
- [ ] Detect unrecoverable auth issues when executing http requests in the server/NangoAction
- [ ] Add queue for server -> client communication
- [ ] Add listener to client SDK to handle incoming messages
- [ ] Add public callback registration method on client SDK

#### Docs
- [ ] Add new behaviour to NangoAction reference
- [ ] Document auth callback behaviour in auth guide
- [ ] Update client SDK reference

**Comment by bastienbeurier** [comment]
Closing for now since it belonged to a previous iteration of the product and would need to be restructured for this one.
