### ISSUE TITLE
CLI: add-integration command

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#8]
## Objective
Make it easy to add a new integration by providing a command with the CLI for that.
Could look like this:
```npx nango add-integration```

And maybe take optional parameters for the integration name. If omitted this could be asked from the user.
The command should create the subdirectory for the integration and edit the integrations.yaml file to add a default scaffold for the integration. An example of this scaffold can be found in the [add an integration guide](https://docs.nango.dev/guides/create-an-integration)

## Tasks
There are some common dependencies between this issue and #5, e.g. making sure the command is run from within a nango-integrations folder (or knowing which one to use). If you want to pick one up, #5 is probably somewhat easier to implement first.

- [ ] Add the `add-integration` command to the CLI
- [ ] Make sure the CLI has decent help built-in on how to use the command

#### Docs
- [ ] Update quickstart with CLI command instead of the manual copy & paste
- [ ] Update the "Create an integration" guide to use the CLI command

**Comment by bastienbeurier** [comment]
No longer needed (no more client-side integration files).
